name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Apply infrastructure
        run: export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY }}" && export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_KEY }}" && terraform init && terraform apply -auto-approve